### PR TITLE
Upgrades can now be applied to vanilla chests, and there are now upgrades for each tier to every single higher tier

### PR DESCRIPTION
**Pull request by foul-fortune-feline**
Removed the wooden chest as a result of the fact it's no longer needed, upgrades fully function on the vanilla chests now

### CODE REVIEW

**Comment by 4nner** [comment]
Thank you for your contribution. I will review the code tomorrow morning, and merge it. I will then release the new versions shortly after.

**Comment by foul-fortune-feline** [comment]
> Thank you for your contribution. I will review the code tomorrow morning, and merge it. I will then release the new versions shortly after.
No problem haha. I also went to the trouble of adding all the upgrades that make sense, so it's a bit more deserving of a minor version increase now~

**Comment by 4nner** [comment]
Oh wow, thanks for these additions. I will start reviewing the code and then merge it

**Review by 4nner — APPROVED** [review]
Everything looks fine. Crafting recipes seem to be well balanced. 
Thank you again for your contribution. This PR is ready to be merged.

**Pull request merged**
